FROM                            almalinux:9
CMD                            ["google.com"]


step2:
=====
FROM                            almalinux:9
ENTRYPOINT                     ["ping","-c5","google.com"]

step3:
=====
FROM                            almalinux:9
CMD                             ["google.com"]
ENTRYPOINT                     ["ping","-c5"]