FROM                       almalinux:9
# ADD                        https://github.com/pdevops78/learn-docker/blob/main/COPY/Dockerfile /tmp/sample.txt
ADD                         https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip /tmp/frontend/
CMD                        ["sleep","100"]