FROM                       almalinux:9
# ADD                        https://github.com/pdevops78/learn-docker/blob/main/COPY/Dockerfile /tmp/sample.txt
ADD                         https://getsamplefiles.com/download/tar/sample-1.tar /tmp/
 CMD                        ["sleep","100"]